_includes/process.md

small typo in process documentation

---

index.md

Add Itamae to management tools.

---

advanced_tips.md

Small change to documentation.

Grammar fix. Change 'temporary' to 'temporarily'.

---

_includes/x509_certificate.md
_includes/x509_private_key.md
resource_types.md

Documentation for x509_certificate, x509_private_key, https://github.com/serverspec/serverspec/pull/507

integrate x509 docs

---

_includes/file.md

Hello,
Please see below proposed pull request. We are using the be_mode function and found the documentation does not cover its use.
thanks
Luke

added be_mode documentaion as the octet matching is not coverd

---

_includes/process.md

See https://github.com/serverspec/serverspec/blob/master/lib/serverspec/type/process.rb#L8-L14

Better examples for type process

---

resource_types.md

meh, forgot an entry in resource_types.md, sorry :)

fix italics, 2nd try

---

_includes/docker_container.md
_includes/docker_image.md
resource_types.md

add resource type documentation to web site.

add docs for docker_image, docker_container

---

_includes/bond.md
_includes/bridge.md
_includes/interface.md

Just some typo fixes for `bond.md`, 'bridge.md` and `interface.md`. :)

Typo fixes

---

_includes/interface.md

reference
---
- Interface up? serverspec/serverspec#518

Add "be_up" matcher of Interface

---

_includes/docker_image.md

Related to serverspec/serverspec#482.

Update documentation of docker_image

---

_includes/file.md

- serverspec/serverspec#523
- serverspec/specinfra#403

Add document for block_device and character_device

---

_includes/file.md

Sorry! :sweat: 
PR #61 had a wrong syntax that does not escape _underscore_.

Escape underscores

---

_includes/file.md

Add documentation about file exist matcher

---

host_inventory.md

Documenting the special case with the Solaris swap files systems.

host_inventory: Documenting multiple swap file systems in solaris

---

host_inventory.md

Documenting the the virtualization keyword.

host_inventory/virtualization: documenting this call

---

_includes/selinux_module.md
resource_types.md

Adding the selinux_module documentation.

type/selinux_module: Adding doc

---

_includes/selinux.md

This request relies on serverspec's pull request 530 ->  https://github.com/mizzy/serverspec/pull/530

selinux: adding the with_policy matcher

---

_includes/user.md

Note: This pull request depends on serverspec's pull request #534 -> https://github.com/mizzy/serverspec/pull/534

user: adding :encrypted_password matcher

---

advanced_tips.md

Obsoleted since https://github.com/mizzy/serverspec/pull/465

Fix old return_stdout syntax for command ressource

---

_includes/service.md

Depends on serverspec pull request #556

Document the with_name matcher for be_monitored_by

---

_includes/docker_container.md

for
- exists (be_present)
- docker inspect

Update docker_container examples

---

_includes/x509_certificate.md

Doc for https://github.com/mizzy/serverspec/pull/570

Add documentation for X509Certificate#subject_alt_names

---

_includes/file.md

add document for mizzy/serverspec#567

add document of its(:content_as_yaml) for file resource type

---

_includes/file.md

add document for mizzy/serverspec#566

add document of its(:content_as_json) for file resource type

---

host_inventory.md

Adding documentation for user, group, facter, and ohai in `host_inventory`.

Host inventory additions
