serverspec/serverspec.github.io

_includes/x509_certificate.md, _includes/x509_private_key.md
Markdown turned _.._ into italics, preview on gh was ok but on the website its interpreted differently.
=> fix markdown italics for x509 stuff

_includes/bridge.md, _includes/interface.md, _includes/selinux.md
This PR is tiny fix.....
I just noticed this, when I exec following command to generate https://github.com/k1LoW/emacs-serverspec/blob/master/dict/serverspec 
```
$ curl http://serverspec.org/resource_types.html | grep h4 | sed 's/<\/*h4>//g' | sort | uniq
```
=> Uniform html tag for 'matcher'

_includes/command.md
HI,
I wrote a usage of [RP-513:Contain matcher for command outputs](https://github.com/serverspec/serverspec/pull/513)
=> Usage of https://github.com/serverspec/serverspec/pull/513

advanced_tips.md
sudo_optionsの指定が便利でしたがTipsになかったので。
こちらの実装を参考にしました。
https://github.com/serverspec/specinfra/blob/master/lib/specinfra/backend/ssh.rb#L159-L163
=> Add usage of sudo_options to advanced tips

advanced_tips.md
Noticed a few items in the code examples for the `shared_examples` section that don't line with the each other or the descriptions.
=> Fixes a few advanced_tips items for clarity

_includes/port.md, _includes/selinux.md, _includes/x509_certificate.md
Just some minor typo fixes for `_includes/x509_certificate.md`, `_includes/port.md` and `_includes/selinux.md`.
=> Typo fixes

_includes/file.md
A colleague asked me the other day how to get the selinux label. I showed him by using the source. I thought updating the documentation is a better use of my time ;).
Also added be_pipe and :size. For the be_immutable I sent a patch into specinfra so that it should work even with RHEL.
=> file.md: adding be_pipe, be_immutable, :selinux_label and size

tutorial.md
Menu isn't being rendered due to the wrapping HTML element (http://serverspec.org/tutorial.html)
I've edited the page to be consistent with the *Resource Types* page.
=> Removed wrapping HTML element, moved markdown to be consistent with other pages

_includes/host.md
Note: This pull request depends on serverspec's pull request 529 -> https://github.com/mizzy/serverspec/pull/529
=> host: Documenting new keywords its(:ipv4_address) and its(:ipv6_address)

host_inventory.md
`host_inventory` got to collect block_device (for Linux).
Collect block device of host inventory
https://github.com/mizzy/specinfra/pull/479
=> Add block_device to host_inventory

_includes/user.md
This is a fix for a formatting error that I missed in the previous commit. Apologies for the extra work.
=> user: fix formating error for the :encrypted_password matcher

_includes/x509_private_key.md
Just found a typo.
has_matching_certificate -> have_matching_certificate
=> Fix typo in x509_private_key.md

_includes/service.md
Serverspec has a support for the matcher `be_running.under('systemd')` against a `service` since https://github.com/mizzy/specinfra/commit/f88ef9ae95628e025cccbf01d449805f20b66d69, which is not currently documented.
This patch adds its documentation!
=> service: Mention be_running.under('systemd')

advanced_tips.md
:red_circle: With actual pattern, rspec goes like this : 
```bash
rspec --pattern spec/base,myrole/\*_spec.rb
```
So it is searching for a folder named `base,myrole`
:white_check_mark:  Whith the fix, rspec goes like : 
```bash
rspec --pattern spec/{base,myrole}/\*_spec.rb
```
So it is searching for folders `base` and `myrole`
=> Fix pattern matching string

_includes/user.md
Summary:
* Documenting belong to primary group.
* Fixing a typo in the :encrypted_password regex for sha-512
=> Adding belong_to_primary_group to "user"

_includes/process.md
Found an undocumented attribute matcher in the process type.
=> Adding :count attribute matcher to type process

_includes/interface.md
Updating documentation for mizzy/serverspec#559.
=> its(:ipv4/v6_address) feature in interface resource documentation

host_inventory.md
Noticed two host_inventory hashes from specinfra missing from the documentation so I added them.
=> adding missing kernel and cpu doc to host_inventory

_layouts/layout.html, advanced_tips.md
In this PR:
* Documentation for shared examples parameters, which come handy to improve reuse. I thought it was worth documenting, because it wasn't immediate to understand these are actually a direct use of RSpec shared examples.
* A link to the documentation repository (because it took me quite some time to figure out where it was).
As a meta-note, I had issues rendering the site locally (some unclear trouble with redcarpet). Updating `gh-pages` and removing `markdown: redcarpet` solved the issue for me.
=> Documentation improvements

_includes/file.md
Escape dots in regex `ServerName www.example.jp` example, otherise e.g. `ServerName wwwwexample.jp` would match, too.
=> Escape dots in regex for ServerName
